spring:
  datasource:
   url: jdbc:postgresql://localhost:5431/patient_db
   driver-class-name: org.postgresql.Driver
   username: admin
   password: password


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8005



