

server:
  port: 4000


spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017
      port: 27017
      database: Guard_DB


secrets:
  jwt-secret-key: YYwzirRgOIRLejdymwtcw1IyWlYGVd5sfeIT3807hfPyVTFBqjVIBI7PatO8DLXt

