
server:
  port: 8002



spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/Patient_db
   driver-class-name: org.postgresql.Driver
   username: admin
   password: password



  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  instance:
    prefer-ip-address: true


